# -*- coding: utf-8 -*-
"""Software Now Assign 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGPZkNgFuy6PkNrn61BsEJ6DwWUM8034
"""

import os

"""
HIT-137: Group Assignment 2-Q1

Group Name: DAN/EXT 06
Group Members:
1. Mahmuda Haque Mumu      - S393941
2. Hossain Md Atiquzzaman  - S396158
3. Arifeen Hossain Chaman  - S403298
4. Md Shafiul Abedin       - S395472

Custom Shift Cipher: Encrypt, Decrypt, and Verify

Encryption Rules:
  Lowercase letters:
    a-m (first half): shift FORWARD by shift1 * shift2 positions  -> tagged "1"
    n-z (second half): shift BACKWARD by shift1 + shift2 positions -> tagged "2"
  Uppercase letters:
    A-M (first half): shift BACKWARD by shift1 positions           -> tagged "1"
    N-Z (second half): shift FORWARD by shift2^2 positions         -> tagged "2"
  Other characters (spaces, digits, symbols, newlines):            -> tagged "0"

Tags are embedded in the encrypted file to allow perfect decryption.
"""

# All file paths are relative to the directory this script lives in,
# so the program works correctly regardless of where you run it from.
RAW_PATH        = "raw_text.txt"
ENCRYPTED_PATH  = "encrypted_text.txt"
DECRYPTED_PATH  = "decrypted_text.txt"


def encrypt_text(text, shift1, shift2):
    """
    Encrypt a string using the custom shift cipher.
    Each character is encrypted and tagged ("1", "2", or "0") to record
    which rule was applied, enabling perfect decryption.
    """
    encrypted = ""
    for ch in text:
        if ch.islower():
            pos = ord(ch) - ord('a')
            if pos <= 12:                               # a-m: forward by shift1 * shift2
                new_pos = (pos + shift1 * shift2) % 26
                encrypted += chr(new_pos + ord('a')) + "1"
            else:                                       # n-z: backward by shift1 + shift2
                new_pos = (pos - (shift1 + shift2)) % 26
                encrypted += chr(new_pos + ord('a')) + "2"

        elif ch.isupper():
            pos = ord(ch) - ord('A')
            if pos <= 12:                               # A-M: backward by shift1
                new_pos = (pos - shift1) % 26
                encrypted += chr(new_pos + ord('A')) + "1"
            else:                                       # N-Z: forward by shift2^2
                new_pos = (pos + shift2 ** 2) % 26
                encrypted += chr(new_pos + ord('A')) + "2"

        else:                                           # spaces, digits, symbols, etc.
            encrypted += ch + "0"

    return encrypted


def decrypt_text(text, shift1, shift2):
    """
    Decrypt a string that was encrypted with encrypt_text().
    Reads each (character, tag) pair and applies the exact inverse operation.
    """
    decrypted = ""
    i = 0
    while i < len(text):
        ch  = text[i]
        tag = text[i + 1]
        i += 2

        if ch.islower():
            pos = ord(ch) - ord('a')
            if tag == "1":                              # reverse of first-half rule
                new_pos = (pos - shift1 * shift2) % 26
            else:                                       # reverse of second-half rule
                new_pos = (pos + shift1 + shift2) % 26
            decrypted += chr(new_pos + ord('a'))

        elif ch.isupper():
            pos = ord(ch) - ord('A')
            if tag == "1":                              # reverse of first-half rule
                new_pos = (pos + shift1) % 26
            else:                                       # reverse of second-half rule
                new_pos = (pos - shift2 ** 2) % 26
            decrypted += chr(new_pos + ord('A'))

        else:
            decrypted += ch                             # non-letter: restore as-is

    return decrypted


def encrypt(shift1, shift2):
    """
    Read raw_text.txt, encrypt its contents, and write to encrypted_text.txt.
    Both files are located in the same folder as this script.
    """
    if not os.path.exists(RAW_PATH):
        print(f"Error: Could not find '{RAW_PATH}'.")
        print("Make sure 'raw_text.txt' is in the same folder as this script.")
        return None

    with open(RAW_PATH, "r", encoding="utf-8") as f:
        raw = f.read()

    encrypted = encrypt_text(raw, shift1, shift2)

    with open(ENCRYPTED_PATH, "w", encoding="utf-8") as f:
        f.write(encrypted)

    print(f"Encryption complete  ->  {ENCRYPTED_PATH}")
    return encrypted


def decrypt(shift1, shift2):
    """
    Read encrypted_text.txt, decrypt its contents, and write to decrypted_text.txt.
    Both files are located in the same folder as this script.
    """
    with open(ENCRYPTED_PATH, "r", encoding="utf-8") as f:
        encrypted = f.read()

    decrypted = decrypt_text(encrypted, shift1, shift2)

    with open(DECRYPTED_PATH, "w", encoding="utf-8") as f:
        f.write(decrypted)

    print(f"Decryption complete  ->  {DECRYPTED_PATH}")
    return decrypted


def verify():
    """
    Compare raw_text.txt with decrypted_text.txt and print the result.
    """
    with open(RAW_PATH, "r", encoding="utf-8") as f:
        original = f.read()
    with open(DECRYPTED_PATH, "r", encoding="utf-8") as f:
        decrypted = f.read()

    if original == decrypted:
        print("Verification SUCCESSFUL: Decrypted text matches the original.")
    else:
        mismatches = sum(1 for a, b in zip(original, decrypted) if a != b)
        mismatches += abs(len(original) - len(decrypted))
        print(f"Verification FAILED: {mismatches} character(s) differ.")
        for i, (a, b) in enumerate(zip(original, decrypted)):
            if a != b:
                print(f"  First mismatch at index {i}: "
                      f"original={repr(a)}, decrypted={repr(b)}")
                break


def main():
    print("=" * 45)
    print("  HIT137 Assignment 2 - Question 1")
    print("  Custom Shift Cipher")
    print("=" * 45)
    print()

    # Check if raw_text.txt exists, if not, create it with default content
    raw_text_filename = "raw_text.txt"
    if not os.path.exists(raw_text_filename):
        print(f"'{raw_text_filename}' not found. Creating it with default content.")
        default_content = "Hello, World! This is a test message for encryption."
        with open(raw_text_filename, "w", encoding="utf-8") as f:
            f.write(default_content)
        print(f"'{raw_text_filename}' created with default content.")

    # Step 1: Prompt the user for shift values
    while True:
        try:
            shift1 = int(input("Enter shift1 (integer): "))
            shift2 = int(input("Enter shift2 (integer): "))
            break
        except ValueError:
            print("  Error: Please enter valid integers.\n")

    print()

    # Step 2: Encrypt raw_text.txt -> encrypted_text.txt
    result = encrypt(shift1, shift2)
    if result is None:
        return          # raw_text.txt was missing — stop early

    # Step 3: Decrypt encrypted_text.txt -> decrypted_text.txt
    decrypt(shift1, shift2)

    # Step 4: Verify decrypted text matches the original
    verify()

    print()
    print("Done.")


if __name__ == "__main__":
    main()



